server:
  port: 8740
spring:
  redis:
    database: 1
    host: 58.84.55.36
    password: fanyu@2018
    port: 6379
    timeout: 3000
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000
    testOnBorrow: true
  application:
    name: okToken-user-server
  profiles:
    active: dev
  datasource:
    name: test
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.fykj.cloud.model.entity
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers: com.fykj.cloud.commons.tkmapper.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql



eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

feign:
  hystrix:
    enabled: false




#hystrix:
#  threadpool:
#    default:
#      coreSize: 200
#      maxQueueSize: 200
#      queueSizeRejectionThreshold: 50
#  command:
#    execution:
#      isolation:
#        thread:
#          timeoutInMilliseconds: 600000
#    circuitBreaker:
#      requestVolumeThreshold: 50

# 打印sql
logging:
  level:
    com.fykj.cloud.userserver.mapper: debug
ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
#  eager-load:
#    clients: epaper-login-server,epaper-basics-server,epaper-order-server
#    enabled: true